name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
        # Execute unit tests
    - name: Unit Test with Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.14.3
      with:
          api-level: 29
          script: ./gradlew connectedCheck
        # run: ./gradlew testDebugUnitTest

    - name: generate report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: app/build/reports/coverage/debug


    - name: Download Test Reports Folder
      uses: actions/download-artifact@v2
      with:
        name: report
        path: app/build/reports/coverage/debug

    - name: Upload Test Report
      uses: codecov/codecov-action@v2
      with:
        files: "app/build/reports/coverage/debug/report.xml"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
         token: ${{ secrets.CODECOV_TOKEN }}
